# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_client_hospital_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='*Client name is required', max_length=50),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='due_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pregnancy',
            name='week_care_commences',
            field=models.IntegerField(blank=True, default=4),
        ),
    ]
